# Generated by Django 4.1.7 on 2023-04-11 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
    ]
