# Generated by Django 4.1.7 on 2023-04-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_remove_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='meter_number',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
