# Generated by Django 4.1.7 on 2023-04-11 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_client_meter_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.client')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.administrator')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.reportproblem')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.TextField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_payed', models.DateTimeField(auto_now=True)),
                ('security_key', models.CharField(max_length=10)),
                ('status', models.TextField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Expired', 'Expired')], null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.client')),
            ],
        ),
    ]
