# Generated by Django 4.1.7 on 2023-04-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_client_appartment_name_client_appartment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbill',
            name='meter_consumption',
            field=models.IntegerField(default=0),
        ),
    ]
