# Generated by Django 4.1.7 on 2023-04-21 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_alter_waterbill_meter_consumption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
