# Generated by Django 4.1.7 on 2023-04-21 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_remove_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbill',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='Main.client'),
        ),
    ]
