# Generated by Django 4.1.7 on 2023-04-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_remove_payment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbill',
            name='cost',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='waterbill',
            name='status',
            field=models.TextField(choices=[('Paid', 'Paid'), ('pending', 'pending')], null=True),
        ),
    ]
