# Generated by Django 4.1.7 on 2023-04-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_waterbill_cost_alter_waterbill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='usage',
            field=models.TextField(choices=[('Household', 'Household'), ('Commercial', 'Commercial')], default='Household'),
        ),
    ]
